!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  footprint: '[[0.2,0.2],[-0.2,0.2],[-0.2,-0.2],[0.2,-0.2]]'
  footprint_padding: 0.1
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      footprint: '[[0.2,0.2],[-0.2,0.2],[-0.2,-0.2],[0.2,-0.2]]'
      footprint_padding: 0.1
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      height: 7
      id: 0
      name: Default
      origin_x: 0.0
      origin_y: 0.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      publish_frequency: 10.0
      resolution: 0.05
      robot_radius: 0.69
      state: true
      transform_tolerance: 0.4
      type: ''
      update_frequency: 10.0
      width: 7
    state: []
  height: 7
  origin_x: 0.0
  origin_y: 0.0
  publish_frequency: 10.0
  resolution: 0.05
  robot_radius: 0.69
  transform_tolerance: 0.4
  update_frequency: 10.0
  width: 7
state: []
