!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 1.0
  acc_lim_x: 3.0
  acc_lim_y: 0.0
  angular_sim_granularity: 0.025
  dwa: true
  escape_reset_dist: 0.1
  escape_reset_theta: 1.57079632679
  escape_vel: -1.0
  gdist_scale: 0.3
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 1.0
      acc_lim_x: 3.0
      acc_lim_y: 0.0
      angular_sim_granularity: 0.025
      dwa: true
      escape_reset_dist: 0.1
      escape_reset_theta: 1.57079632679
      escape_vel: -1.0
      gdist_scale: 0.3
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      heading_lookahead: 0.325
      heading_scoring: false
      heading_scoring_timestep: 0.1
      holonomic_robot: false
      id: 0
      max_vel_theta: 3.0
      max_vel_x: 5.0
      min_in_place_vel_theta: 0.0
      min_vel_theta: -3.0
      min_vel_x: 1.0
      name: Default
      occdist_scale: 5.0
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pdist_scale: 2.0
      restore_defaults: false
      sim_granularity: 0.025
      sim_time: 2.0
      simple_attractor: false
      state: true
      type: ''
      vtheta_samples: 30
      vx_samples: 10
      y_vels: -0.3,-0.1,0.1,-0.3
    state: []
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.1
  holonomic_robot: false
  max_vel_theta: 3.0
  max_vel_x: 5.0
  min_in_place_vel_theta: 0.0
  min_vel_theta: -3.0
  min_vel_x: 1.0
  occdist_scale: 5.0
  oscillation_reset_dist: 0.05
  pdist_scale: 2.0
  restore_defaults: false
  sim_granularity: 0.025
  sim_time: 2.0
  simple_attractor: false
  vtheta_samples: 30
  vx_samples: 10
  y_vels: -0.3,-0.1,0.1,-0.3
state: []
