map_type: costmap

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
obstacle_range: 4
raytrace_range: 4
always_send_full_costmap: true

update_frequency: 10.0
publish_frequency: 10.0

#  Time with which to post-date the transform that is published, to indicate that this transform is valid into the future.
transform_tolerance: 0.2    #d=0.1
xy_goal_tolerance: 0.2
yaw_goal_tolerance: 0.1

# footprint: [[0.2, 0.2], [-0.2, 0.2], [-0.2, -0.2], [0.2, -0.2]]
# footprint_padding: 0.1
# For circular robots
#robot_radius: 0.69


    # cost_scaling_factor: 3.0    #1
inflation_radius: 0.6       #0.5
# Inflation Layer Params
# inflation_layer:
    # cost_scaling_factor: 3.0    #1
    # inflation_radius: 0.6       #0.5
