global_costmap:
    global_frame: map
    robot_base_frame: robot_footprint
    # Affects control_loop
    update_frequency: 5.0
    publish_frequency: 5.0
    width: 15.0
    height: 15.0
    resolution: 0.05
    static_map: true
    rolling_window: false

    plugins:
        - {name: static_layer,           type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer,         type: "costmap_2d::VoxelLayer"}
        - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    # NOTE: LOCAL Obstacle Layer is ObstacleLayer, GLOBAL Obstacle Layer is VoxelLayer