local_costmap:
    global_frame: odom
    robot_base_frame: robot_footprint
    # Affects map update loop
    update_frequency: 10.0
    publish_frequency: 10.0
    width: 7
    height: 7
    resolution: 0.05
    static_map: false
    # "rolling_window" sets whether the costmap will remain centered around the robot as it moves. If the static_map parameter is set to true, this parameter must be set to false.
    rolling_window: true
