move_base:

    # The rate in Hz at which to run the control loop and send velocity commands to the base.
    controller_frequency: 20                   #d=20

    # How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
    planner_patience: 5                        #d=5

    # How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.
    controller_patience: 15                         #d=15

    # Rate(Hz) to run the global planning loop. If set to 0.0, global planner
    # will only run when new goal is received or the local planner reports that its path is blocked
    planner_frequency: 5                     #d=0
